### ISSUE TITLE
Bug when used with Factorissimo 2

### ISSUE THREAD

**Issue by TokMor** [321freddy/even-distribution#1]
http://imgur.com/a/PuYSl

The Factorissimo2 Buildings have a 'chest entity' that helps to display an overlay over the buildings so players can have an idea of what their buildings do. This chest entity is receiving items from even distribution, but when it does these items disappear into the nether. I asked MagmaMcFry what could be done on his end, but he said that really the only solution is for Even Distribution to have an exclusion set on this entity: "factory-overlay-display".

Would it be possible to set up even distribution to ignore that entity?

See also https://mods.factorio.com/mods/321freddy/even-distribution/discussion/15888

**Comment by 321freddy** [comment]
This seems to affect more than the entity you named here. I'll see what I can do.

In the meantime you can uncheck the "Drop trash to chests" per-player mod setting to prevent this behaviour.

**Comment by Arumba07** [comment]
Thanks, that was the solution we recommended to the server as well.  At least that way we stopped wasting resources for now ;)

**Comment by 321freddy** [comment]
Fixed for version 0.2.5

I also added an "Ignored entities" mod setting, so if you encounter a similar problem again you can add the entity to this list.
