### ISSUE TITLE
Crushes on 0.17.4

### ISSUE THREAD

**Issue by Gibitop** [321freddy/even-distribution#10]
### What I did:
- Loaded Factorio 0.17.4 with even-distribution_0.3.1
- Loaded the map from Factorio 0.16.51
- Selected 18 full stacks of uranium rounds magazine
- Control-dragged them over storage chests (some of them had some items, some didn't)

### What happened:
- Factorio throwed this error:
```Error while running event even-distribution::on_player_fast_transferred (ID 124)
Item stack count has to a be positive number
stack traceback:
	__even-distribution__/scripts/drag.lua:149: in function 'stackTransferred'
	__even-distribution__/scripts/drag.lua:101: in function 'func'
	__even-distribution__/framework.lua:98: in function <__even-distribution__/framework.lua:97>
stack traceback:
	[C]: in function 'remove_item'
	__even-distribution__/scripts/drag.lua:149: in function 'stackTransferred'
	__even-distribution__/scripts/drag.lua:101: in function 'func'
	__even-distribution__/framework.lua:98: in function <__even-distribution__/framework.lua:97>
```
- Factorio closed the map without saving

**Comment by 321freddy** [comment]
Please don't download the mod from this repo, it's still WIP. The official version is on the mod portal: https://mods.factorio.com/mod/even-distribution
