### ISSUE TITLE
Crash during click and drag over ores

### ISSUE THREAD

**Issue by TheVirusWar** [321freddy/even-distribution#11]
As the title says. The game crashes when you try to click and drag over over ores.

![factorio 2019-03-07 19-09-45-75](https://user-images.githubusercontent.com/20507269/53978936-b72b6c00-410c-11e9-88eb-3a11e955221d.png)

**Comment by 321freddy** [comment]
Please don't download the mod from this repo, it's still WIP. The stable version is on the mod portal: https://mods.factorio.com/mod/even-distribution
