### ISSUE TITLE
[Request] Toggable option for showing debug information

### ISSUE THREAD

**Issue by jarquafelmu** [321freddy/even-distribution#12]
I'm not sure which mod is causing the invalid entities that Even Distribution is finding, but could we get a mod setting option in either `map` or `game` which will let us decide whether or not we want to see these debug messages?

![427520_20190321091320_1 (2)](https://user-images.githubusercontent.com/5807272/54762627-103dda00-4bba-11e9-864a-2efc5ccabcea.png)

**Comment by 321freddy** [comment]
These are not debug messages. Your even distribution settings are invalid. What is the value of your "Ignored entities"-setting (see player mod settings)? It should only contain internal entity names like "stone-furnace".

**Comment by jarquafelmu** [comment]
Thank you for the response. I didn't know to look into the `Per Player` settings. For some reason my ignored entities field had `80x80 (4x Roboport Mk2)` as a value. It has now been cleared.
