### ISSUE TITLE
tblId missing local

### ISSUE THREAD

**Issue by BoskiDialer** [321freddy/even-distribution#15]
https://github.com/321freddy/even-distribution/blob/318a089c99750b143a310bc83a96c341dbd71e81/scripts/util.lua#L70

missing local so temporary value with object refs is stored in global context outside of global variable. This is not safe and may desync

```
mod even-distribution has object ref inside _G.tblId.524970.box
mod even-distribution has object ref inside _G.tblId.524973.box
mod even-distribution has object ref inside _G.tblId.524975.box
```

**Comment by 321freddy** [comment]
Fixed for next version
