### ISSUE TITLE
Small improvement

### ISSUE THREAD

**Issue by danyax** [321freddy/even-distribution#22]
I am playing Angel Bob game with tech & component overhaul. I really enjoy mode when all non-placeable items (including fuel) are automatically distributed to machines. Angels componens are not known to mod. I had to  modify code on my local copy in the following way

function setup.generateTrashItemList()
	local items = {}

	for name,item in pairs(game.item_prototypes) do
		if not (item.place_result or item.place_as_equipment_result or item.has_flag("hidden")) then -- or item.place_as_tile_result
			local default = defaultTrash[name] or defaultTrash[item.subgroup.name] or defaultTrash[item.group.name]
			
			if default and default ~= "ignore" then
				if item.fuel_category and not defaultTrash[name] then -- fuels default to 2 stacks as desired amount
					items[name] = 2 * item.stack_size
				else
					items[name] = default
				end
			end
			**_items[name] = 0_**
		end
	end	
	return items
end

This works for both components and fuel.

Would it be possible to add this as option? 

Fuel limit in UI seems to be not respected for coal - if I turn on option "use fuel limits" and set fuel limit it zero, coal still not fully distributed, probably because of default 400 limit set in code. So I have turn off option "use fuel limits" and rely on above code modification.

**Comment by 321freddy** [comment]
Don't modify the code. Just add the items to your logistic requests (or autotrash). This overrides the default values for SHIFT+C.

The fuel limit sets the maximum item count **inside the machines**, not your own. So fuel limit of 100 means that furnaces,  burner inserters, vehicles, etc.  just get 100 fuel items (e.g. coal) each, even if you potentially have more.

**Comment by danyax** [comment]
>> Don't modify the code. Just add the items to your logistic requests (or autotrash). This overrides the default values for SHIFT+C.

This is not a practical options, there hunders on intermediaries in Angel and Bob mods.

>> The fuel limit sets the maximum item count inside the machines, not your own. 
thanks, my bad. It works as intended.

**Comment by 321freddy** [comment]
I already use a bunch of angels and bobs categories:
https://github.com/321freddy/even-distribution/blob/master/default-trash.lua#L23

This could be a bit outdated. If you can tell me the internal names of new groups I can add them.

> auto trashing all non-placeable items seems as good default

That would included some very valuable items like processing units or modules, which some players want to keep so I can't use that as a default.

**Comment by danyax** [comment]
Groups:
resource-refining
angels-smelting
angels-casting
water-treatment
petrochem-refining
angels-fluid-control
bio-processing-nauvis
bio-processing-vegetables
bio-processing-alien
angels-components
angels-blocks
angels-tech
angels-power
angels-logistics
bob-gems

Group "bobmodules" just following subgroups:
module-intermediates
module-intermediates-1
module-intermediates-2

This should cover pretty everything in A&B game and does not contain any valuable pieces

Would it be possible to zero out base limit for all items? May be an option? I have to set zero limits for all items listed your code, as keeping just two metals (iron+copper) out of dozen in A&B makes no sense.

**Comment by 321freddy** [comment]
Added the groups for the next version, thanks for the list!


> Would it be possible to zero out base limit for all items? May be an option? I have to set zero limits for all items listed your code, as keeping just two metals (iron+copper) out of dozen in A&B makes no sense, same for coal. Those predefined limits were meaninful in the past for just base game, but for modded games and given that you added more fine ways to control what is distributed, preconfigiring just small fraction of items (and having no clue in UI what is preconfigured) seems to be unnecessary. I am not complaining, I can continue fixing defaults in code each time mode is updated, but I think other players might have same proble

Well it's not just iron+copper, it keeps some of most modded plates (except angels because his groups are all mixed up), but I agree it's not the best solution and it's hard to see ingame what the default configuration is. I thought about this a little. Zeroing out everything by default, would make it more predictable. But I do like having some sensible limits preconfigured, so I can just jump into a game without having to configure everything first. 

I think what I'm going to do, is zero out all the base limits and automatically add a starting configuration to the logistic slots when starting a new game (few stacks of iron+copper and maybe some modded stuff).

**Comment by danyax** [comment]
This make a lot of sense! New player can see what is preconfigured and change it in UI as needed. I would preconfigure just base game items as it would be quite hard to design and maintain meaningful precofiguration for complex mods. Lets keep is simple!

**Comment by 321freddy** [comment]
Implemented it in version 1.0.2
