### ISSUE TITLE
Error on load with god mode on

### ISSUE THREAD

**Issue by danyax** [321freddy/even-distribution#27]
![20201221195620_1](https://user-images.githubusercontent.com/61344188/102802373-960e3b00-43c7-11eb-8220-1b615afbf13b.jpg)

Happens when loading testing scenario with god mode on. Does not happen when loading normal game.

I cured it by turning off god mode while using old version of mod, then load with new mod version, enabled god mode, saved. Error disappeared.

**Comment by 321freddy** [comment]
Should be fixed in version 1.0.3. Please tell me if not
