### ISSUE TITLE
Shift-C to machine outputs places fuel in furnace output

### ISSUE THREAD

**Issue by bradjshannon** [321freddy/even-distribution#31]
Screenshot below.

When I press shift-C while carrying tons of fuel, I expect Even Distribution to dump fuel (up to a set limit) into nearby machine fuel slots. This does occur.

But the mod additionally places a stack of fuel in the furnaces' output slots, which inserters place on my furnace array's output belt. This has the potential to cause all sorts of problems elsewhere in the factory.

NOTE: I play with a ton of mods. This is my first playthrough with Space Exploration, and the issue involves a fuel type introduced by that mod. I do not know if the issue is specific to this item, or all items from Space Exploration, or fuels from all mods, or all fuels.

![photo_2021-01-01 16 47 13](https://user-images.githubusercontent.com/8301747/103446757-40505300-4c51-11eb-9b41-60da0b4a223d.jpeg)

**Comment by 321freddy** [comment]
Fixed in version 1.0.6. Thanks for the report!
