### ISSUE TITLE
Useless block top left corner

### ISSUE THREAD

**Issue by HopefullyICanChangeThatNameLaterOn** [321freddy/even-distribution#33]
On the top left corner of the screen I noticed a useless block, which is always appearing when having this mod enabled. This is pretty annoying once you noticed it - would be great if you can get rid of it 👍 

Mod version: 1.0.8
Factorio version: 1.1.35

![grafik](https://user-images.githubusercontent.com/40071710/124352848-407eda80-dc03-11eb-9efa-7a90fd8e6abe.png)

**Comment by 321freddy** [comment]
That's weird, i don't have this on my side. You could try removing it with console commands.
