### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by quirkycat** [321freddy/even-distribution#34]
Has been working fine till latest Factorio update.
Factorio 1.1.38 (build 58907, win64, steam)

The mod Even Distribution (1.0.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event even-distribution::on_player_fast_transferred (ID 129)
LuaEntity doesn't contain key x.
stack traceback:
[C]: in function 'index'
__even-distribution/scripts/helpers.lua:21: in function <even-distribution/scripts/helpers.lua:20>
[C]: in function 'create_entity'
even-distribution/scripts/visuals.lua:39: in function 'mark'
even-distribution/scripts/drag.lua:237: in function 'onStackTransferred'
even-distribution/scripts/drag.lua:208: in function 'func'
even-distribution/framework.lua:99: in function <even-distribution/framework.lua:98>

**Comment by 321freddy** [comment]
Fixed in version 1.0.9
