### ISSUE TITLE
Empty UI element in top-left corner

### ISSUE THREAD

**Issue by cemmy410** [321freddy/even-distribution#48]
Factorio version: 1.1
Even Distribution version: 1.0.10

There's an empty UI element in the top-left corner of the game when the Even Distribution mod is enabled:

![image](https://github.com/321freddy/even-distribution/assets/54862465/c67cacb7-50aa-49de-b3ce-91da4d78c7b0)

I've verified that this must be caused by Even Distribution by doing the following:
* Disable Even Distribution. The empty element goes away
* Disable all mods. The empty element goes away
* Disable every mod *except* Even Distribution. The empty element returns

I tried changing all of the configuration options and wasn't able to get it to go away, so I'm assuming this is a bug and not a misconfiguration on my part. It seems to be a very old bug (>3 years) based on a few reddit posts I've found [[1](https://www.reddit.com/r/factorio/comments/1080s1d/what_is_this_thing_in_the_top_left_of_my_screen/)][[2](https://www.reddit.com/r/factorio/comments/p3ifdb/how_do_i_either_remove_or_reaccess_the_tips_panel/)].

I don't know anything about Factorio mods but I am a software developer; if anyone has any ideas as to what's causing this and can point me in the right direction I'm more than happy to try fixing it myself and submitting a PR.

**Comment by 321freddy** [comment]
Fixed in 2.0, delete the mod and load and save the game once to remove the existing element, then you can reinstall again.

**Comment by cemmy410** [comment]
Great, thank you!
