### ISSUE TITLE
non-recoverable error crash

### ISSUE THREAD

**Issue by enkessler** [321freddy/even-distribution#51]
I ran into a crash when trying to swap out ammo on some turrets. Of note, my inventory was completely full at the time, so I wouldn't have had any place for the old ammo to go and the `spill_item_stack` call in the trace suggests that the game was trying to dump the excess onto the ground and that this would not have happened if I had been inserting into empty turrets.

Update: I have confirmed that the above circumstances do reliably reproduce the error. If the game does not have to try to dump items on the ground (either because I leave room in my inventory or there is no ammo to remove from the existing turrets) then no error occurs.

```
The mod Even Distribution (2.0.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event even-distribution::on_tick (ID 0)
__even-distribution__/scripts/helpers/LuaPlayer.lua:152: Arguments count error for 'spill_item_stack': Expected 1 argument but 3 were given
stack traceback:
	[C]: in function 'spill_item_stack'
	__even-distribution__/scripts/helpers/LuaPlayer.lua:152: in function 'returnItems'
	__even-distribution__/scripts/drag.lua:62: in function 'func'
	__even-distribution__/scripts/util.lua:116: in function 'distribute'
	__even-distribution__/scripts/drag.lua:43: in function 'distributeItems'
	__even-distribution__/scripts/drag.lua:19: in function 'func'
	__even-distribution__/framework.lua:49: in function <__even-distribution__/framework.lua:48>
```

![game_crash](https://github.com/user-attachments/assets/35ed3f6f-b300-414f-a020-4c00c34f8b5f)

Hope that helps. Thanks for the mod.

**Comment by 321freddy** [comment]
Fixed in version 2.0.2. Thanks for the report :)
