### ISSUE TITLE
[17.0] Error in Sandbox-mode

### ISSUE THREAD

**Issue by flexoo** [321freddy/even-distribution#8]
Hi, I was just trying something out and filled some gun-turrets with ammo when it crashed.

![error](https://user-images.githubusercontent.com/13826740/53466884-a6636200-3a4b-11e9-9876-15b152453a45.png)

**Comment by 321freddy** [comment]
Fixed in version 0.3.1

Thank you for the report :)

**Comment by flexoo** [comment]
works great, thx for quick fix :)
