### ISSUE TITLE
Crash during inventory cleanup

### ISSUE THREAD

**Issue by Modernkennnern** [321freddy/even-distribution#9]
[log-file](https://pastebin.com/4dtwg2Ty).

Pressing Shift-C (I believe they crash near pipes, but I'm not 100% sure if that's the cause)

**Comment by 321freddy** [comment]
I can't reproduce the crash on my side. Please send me your save file with the steps to reproduce the crash. (You can PM it to me on the forums if you want, username: 321freddy)

**Comment by Modernkennnern** [comment]
Took me a while to get the crash to happen, but I "finally" did.

Sending save now! (I included a screenshot of where I stood when I clicked Shift-C)

**Comment by 321freddy** [comment]
I tried it a couple times but it never crashed on me. This crash is probably caused by factorio itself and not the mod, they might have fixed it by now.

**Comment by novkit** [comment]
I get this crash: 
![image](https://user-images.githubusercontent.com/23021527/57126084-82204c00-6d40-11e9-8b9a-4969dfdf3b6e.png)
when pressing control + C inventory clean up.
[_autosave3.zip](https://github.com/321freddy/even-distribution/files/3141088/_autosave3.zip)
Here is a copy of a save that does it. :D happy bug hunting.
